source/LightData.CMS/Controllers/AccountController.cs
using System.Web.Mvc;
using LightData.Auth.Controllers;

namespace LightData.CMS.Controllers
{
    public class AccountController : SharedController
    {
        //UrlHelper u = new UrlHelper(this.ControllerContext.RequestContext);

        
    }
}

source/LightData.CMS/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using LightData.Auth.Helper;
using LightData.CMS.Controllers.Base;
using LightData.CMS.Modules.Library;

namespace LightData.CMS.Controllers
{
    public class ArticleController : BaseController
    {
        // GET: Article
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ExternalActionResult> Get(int pageNr, string value)
        {
            var articles = await Repository.Get<Article>().Where(x => value == "" || x.ArticleName.Contains(value))
                .Skip((pageNr - 1) * SearchResultValue).Take(SearchResultValue).OrderBy(x => x.ArticleName)
                .LoadChildren().ExecuteAsync();

            return await articles.ToJsonResultAsync();
        }

        [HttpPost]
        public void Save(Article item)
        {
            Repository.Save(item);
            Repository.SaveChanges();
        }

        [HttpPost]
        public void Delete(List<Guid> items)
        {
            items.ForEach(a => Repository.Get<Article>().LoadChildren().Where(x => x.Id == a).Remove());
            Repository.SaveChanges();
        }
   
    }
}

source/LightData.CMS/Controllers/Base/BaseController.cs
using LightData.Auth.Controllers;
using LightData.Auth.Helper;
using LightData.CMS.Modules.Library;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LightData.CMS.Controllers.Base
{
    public class BaseController : SharedController
    {
        private EntityWorker.Core.InterFace.IRepository _repository;

        protected EntityWorker.Core.InterFace.IRepository Repository
        {
            get
            {
                if (_repository == null)
                    _repository = new LightData.CMS.Modules.Repository.Repository();
                return _repository;
            }
        }

        [HttpPost]
        public ExternalActionResult GetActiveCountries()
        {
            return Repository.Get<Country>().Where(x => x.Visible == true).Execute().ToJsonResult();
        }

        [HttpPost]
        public async Task<ExternalActionResult> GetCountries(string filter)
        {
            var countries = await Repository.Get<Country>().Where(x => string.IsNullOrEmpty(filter) || filter.Contains(x.Name)).ExecuteAsync();

            return await countries.ToJsonResultAsync();
        }

        [HttpPost]
        public void SaveCountry(Country country)
        {
            Repository.Save(country);
        }
    }
}

source/LightData.CMS/Controllers/HomeController.cs
using System.Web.Mvc;
using LightData.Auth.Controllers;


namespace LightData.CMS.Controllers
{
    public class HomeController : SharedController
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

source/LightData.CMS/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using EntityWorker.Core.Helper;
using LightData.Auth.Helper;
using LightData.CMS.Controllers.Base;
using LightData.CMS.Modules.Library;

namespace LightData.CMS.Controllers
{
    public class MenusController : BaseController
    {
        // GET: Menus
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ExternalActionResult> GetMenus()
        {
            var menus = await Repository.Get<Menus>().LoadChildren().Where(x => x.ParentId == null).ExecuteAsync();
            return await menus.ToJsonResultAsync();
        }

        [HttpPost]
        public async Task<ExternalActionResult> GetAutoFillData(string value)
        {
            var menus = new List<Menus>();
            var id = value?.ConvertValue<Guid?>();
            if (id.HasValue)
                menus = await Repository.Get<Menus>().Where(x => x.Id == id).ExecuteAsync();
            else
                menus = await Repository.Get<Menus>().LoadChildren()
                    .Where(x => x.DisplayName.Contains(value) || x.Children.Any(a => a.DisplayName.Contains(value)))
                    .ExecuteAsync();
            return await menus.ToJsonResultAsync();

        }

        [HttpPost]
        public void Save(Menus item)
        {
            Repository.Save(item);
            Repository.SaveChanges();
        }

        [HttpPost]
        public void Delete(Menus item)
        {
            Repository.Delete(item);
            Repository.SaveChanges();
        }

    }
}

source/LightData.CMS/Controllers/SliderController.cs
using LightData.Auth.Helper;
using LightData.CMS.Controllers.Base;
using LightData.CMS.Modules.Library;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;
using System;

namespace LightData.CMS.Controllers
{
    public class SliderController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ExternalActionResult> Get()
        {
            var sliderCollection = await Repository.Get<SliderCollection>().LoadChildren().IgnoreChildren(x =>
            x.Sliders.Select(a => a.File.Folder),
            x => x.Sliders.Select(a => a.File.Slider),
            x => x.Sliders.Select(a => a.SliderCollection)).ExecuteAsync();
            return await sliderCollection.ToJsonResultAsync();
        }

        [HttpPost]
        public void Save(SliderCollection item)
        {
            Repository.Save(item);
            Repository.SaveChanges();
        }

        [HttpPost]
        public void Delete(Guid itemId)
        {
            Repository.Get<SliderCollection>().Where(x => x.Id == itemId).IgnoreChildren(x => x.Sliders.Select(a => a.File), x => x.Sliders.Select(a => a.File.Slider), x => x.Sliders.Select(a => a.SliderCollection)).LoadChildren().Remove().SaveChanges();

        }

        [HttpPost]
        public void DeleteSlider(Guid itemId)
        {
            Repository.Get<Slider>().Where(x => x.Id == itemId).Remove().SaveChanges();
        }
    }
}

source/LightData.CMS/Views/_SharedLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script>
        var globalSettings =
        {
            setValue: '@Url.Action("SetValue", "Menus")',
            getValue: '@Url.Action("GetValue", "Menus")',
            htmlFormater: '@Url.Action("HtmlFormater", "Menus", new { }, this.Request.Url.Scheme)',
        };
    </script>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/jquery")

    <script>
        globalSettings.theme = $.themeLoader({ getUri: '@Url.Action("GetTheme", "FileUploader", new { }, this.Request.Url.Scheme)' });
    </script>

    @*@foreach (var file in new LightData.CMS.Modules.Repository.Repository().Get<LightData.CMS.Modules.Library.FileItem>().Where(x =>
         x.FileType == LightData.CMS.Modules.Helper.EnumHelper.AllowedFiles.CSS || x.FileType == LightData.CMS.Modules.Helper.EnumHelper.AllowedFiles.JAVASCRIPT).Execute())
        {
            if (file.FileType.ToString() == "JAVASCRIPT")
            {
                <script type="text/javascript" src='@Url.Action("LoadFiles", "FileUploader", new { }, this.Request.Url.Scheme)?fileId=@file.Id'></script>
            }
            else
            {
                <link class="ExternalCss" href='@Url.Action("LoadFiles", "FileUploader", new { }, this.Request.Url.Scheme)?fileId=@file.Id' rel="stylesheet" />
            }
        }*@

    <title>@ViewBag.Title</title>

</head>
<body>
    <div id="siteContainer">
        <div id="cssmenu">
        </div>
        <div id="containerRight">
            <nav class="menus"></nav>

        </div>
        <div id="centerContent">
            @RenderBody()
        </div>


    </div>
    <script>

        var base = {
            getActiveCountries: function () {
                var result = [];
                $("body").LightDataAjax({
                    contentType: "application/json",
                    dataType: "json",
                    type: "POST",
                    async: false,
                    url: '@Url.Action("GetActiveCountries", "Article")',
                    success: function (data) {
                        result = data;
                        return true;
                    }
                });
                return result;
            },

            saveCountry: function (country) {
                  $("body").LightDataAjax({
                    contentType: "application/json",
                    dataType: "json",
                    type: "POST",
                    async: false,
                    data: JSON.stringify(country),
                    url: '@Url.Action("SaveCountry", "Article")',
                    success: function (data) {
                        result = data;
                        return true;
                    }
                });
            },
            getCountries: function (filter) {
                var result = [];
                $("body").LightDataAjax({
                    contentType: "application/json",
                    dataType: "json",
                    type: "POST",
                    async: false,
                    data: { filter: filter},
                    url: '@Url.Action("GetCountries", "Article")',
                    success: function (data) {
                        result = data;
                        return true;
                    }
                });
                return result;
            }

        }


        $(document).ready(function () {
            $.toolTipIni();
            $.checkBox();
            $.inputValidator();
            var timeOut = undefined;
            function floatFix() {
                $("#containerRight").css({ "min-height": $(window).height() - 50 });
                var rightMenu = $("#containerRight")[0].getBoundingClientRect().width + 25;
                var centerMenu = $("#centerContent");
                var windowWidth = $(window).width()
                centerMenu.css("max-width", (windowWidth - rightMenu));



                if (timeOut === undefined)
                $(window).resize(function () {
                    clearTimeout(timeOut);

                    timeOut = setTimeout(floatFix, 70);
                });
            }

            floatFix();
            $("#cssmenu").horizontalMenu({
                datasource: [
                    {
                        id: 1,
                        uri: "/CMS/Article/index",
                        displayName: "Manage Articles",
                        children: [
                            {
                                id: 2,
                                uri: "#",
                                displayName: "Overview",
                                children: [
                                    {
                                        id: 3,
                                        uri: "#",
                                        displayName: "Overview 2"
                                    },
                                    {
                                        id: 4,
                                        uri: "#",
                                        displayName: "Overview 3"
                                    }
                                ]

                            }
                        ]
                    },
                    {
                        id: 1,
                        uri: "/CMS/fileuploader",
                        displayName: "Manage Theme Files",
                        children: [{
                            id: 5,
                            uri: "/CMS/Slider/index",
                            displayName: "Manage Slider"
                        }]
                    },
                    {
                        id: 1,
                        uri: "#",
                        displayName: "Create Menussdsd"
                    }
                ]
            });
        });
    </script>

    <script>
    $(".menus").menus({
        getUri: '@Url.Action("GetMenus", "Menus")',
        header: "Manage Menus",
        autoFillDataUrl: '@Url.Action("GetAutoFillData", "Menus")',
        saveUri: '@Url.Action("Save", "Menus")',
        deleteUri: '@Url.Action("Delete", "Menus")'
    });
    </script>

</body>

</html>